"""Add is_used to Component model

Revision ID: 907bd354ec34
Revises: 
Create Date: 2026-02-14 10:41:53.404291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907bd354ec34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_used', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_column('is_used')

    # ### end Alembic commands ###
